#!/usr/bin/env bash
# FROZEN validation for step 3.1. Do not edit this file.
# Usage: bash .oplan/word-quiz/validate-3.1.sh
set -o pipefail

root=$(git rev-parse --show-toplevel) || { echo "FAIL: not in a git repo"; exit 1; }
cd "$root" || { echo "FAIL: cannot cd to repo root"; exit 1; }

if ! node --check lib/profile.js; then
  echo "FAIL: node --check lib/profile.js"
  exit 1
fi

if [ ! -f tests/profile-quiz-schema.test.js ]; then
  echo "FAIL: tests/profile-quiz-schema.test.js does not exist"
  exit 1
fi

out=$(npm test 2>&1)

case "$out" in
  *"# fail 0"*) ;;
  *) echo "FAIL: npm test did not print '# fail 0'"; printf '%s\n' "$out" | tail -14; exit 1 ;;
esac

case "$out" in
  *"# pass 231"*) ;;
  *) echo "FAIL: npm test did not print '# pass 231'"; printf '%s\n' "$out" | tail -14; exit 1 ;;
esac

echo STEP-3.1-OK
