#!/usr/bin/env bash
# FROZEN validation for step 3.5. Do not edit this file.
# Usage: bash .oplan/word-quiz/validate-3.5.sh
set -o pipefail

root=$(git rev-parse --show-toplevel) || { echo "FAIL: not in a git repo"; exit 1; }
cd "$root" || { echo "FAIL: cannot cd to repo root"; exit 1; }

if [ ! -f tests/profile-quiz-scenario.test.js ]; then
  echo "FAIL: tests/profile-quiz-scenario.test.js does not exist"
  exit 1
fi

# This step is allowed to MUTATE lib/ and api/ temporarily to produce failure
# evidence, and is required to restore them. A self-reported hash proves nothing;
# this does. Checked before anything else that could be fooled by a live mutation.
if ! git diff --quiet lib/ api/; then
  echo "FAIL: lib/ or api/ was left modified -- a mutation was not restored"
  git diff --stat lib/ api/
  exit 1
fi

# Boundary: this step may leave exactly ONE file changed.
changed=$(git status --porcelain -- . ':(exclude).oplan' | awk '{print $NF}' | sort | tr '\n' ' ')
expected='tests/profile-quiz-scenario.test.js '
if [ "$changed" != "$expected" ]; then
  echo "FAIL: files outside the step boundary changed."
  echo "  changed:  [$changed]"
  echo "  expected: [$expected]"
  exit 1
fi

out=$(npm test 2>&1)

case "$out" in
  *"# fail 0"*) ;;
  *) echo "FAIL: npm test did not print '# fail 0'"; printf '%s\n' "$out" | tail -14; exit 1 ;;
esac

case "$out" in
  *"# pass 257"*) ;;
  *) echo "FAIL: npm test did not print '# pass 257'"; printf '%s\n' "$out" | tail -14; exit 1 ;;
esac

if [ -e .data/profile.json ]; then
  echo "FAIL: .data/profile.json exists -- a test ran against the REAL data dir"
  exit 1
fi

echo STEP-3.5-OK
