#!/usr/bin/env bash
# FROZEN validation for step 3.4. Do not edit this file.
# Usage: bash .oplan/word-quiz/validate-3.4.sh
set -o pipefail

root=$(git rev-parse --show-toplevel) || { echo "FAIL: not in a git repo"; exit 1; }
cd "$root" || { echo "FAIL: cannot cd to repo root"; exit 1; }

if ! node --check api/profile.js; then
  echo "FAIL: node --check api/profile.js"
  exit 1
fi

if [ ! -f tests/api-profile-quiz.test.js ]; then
  echo "FAIL: tests/api-profile-quiz.test.js does not exist"
  exit 1
fi

# Boundary: this step may touch exactly two files.
changed=$(git status --porcelain -- . ':(exclude).oplan' | awk '{print $NF}' | sort | tr '\n' ' ')
expected='api/profile.js tests/api-profile-quiz.test.js '
if [ "$changed" != "$expected" ]; then
  echo "FAIL: files outside the step boundary changed."
  echo "  changed:  [$changed]"
  echo "  expected: [$expected]"
  exit 1
fi

out=$(npm test 2>&1)

case "$out" in
  *"# fail 0"*) ;;
  *) echo "FAIL: npm test did not print '# fail 0'"; printf '%s\n' "$out" | tail -14; exit 1 ;;
esac

case "$out" in
  *"# pass 252"*) ;;
  *) echo "FAIL: npm test did not print '# pass 252'"; printf '%s\n' "$out" | tail -14; exit 1 ;;
esac

# A read that writes: GET /api/profile CREATES a profile when absent. Every test
# must point DATA_DIR at a temp dir, so the real one must still be untouched.
if [ -e .data/profile.json ]; then
  echo "FAIL: .data/profile.json exists -- a test ran against the REAL data dir"
  exit 1
fi

echo STEP-3.4-OK
